version: "3"
services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    image: node
    container_name: "node-server"
    volumes:
      - .:/root
    network_mode: "host"
    command: /bin/bash
